import config.configurationKotlinSerialization
import config.configureAndroidCompose
import config.configureAndroidLibrary
import config.configureAndroidTest
import config.configureHiltAndroid
import config.configureKotlinTest

configureAndroidLibrary()

configurationKotlinSerialization()

configureAndroidTest()
configureKotlinTest()