import config.configureAndroidCompose
import config.configureAndroidLibrary
import config.configureAndroidTest
import config.configureHiltAndroid
import config.configureKotlinTest

configureAndroidLibrary()
configureAndroidCompose()
configureAndroidTest()
configureKotlinTest()
configureHiltAndroid()